### ISSUE TITLE
Interface usage

### ISSUE THREAD

**Issue by vba** [hhblaze/DBreezeBased#1]
Could you please use interfaces where possible instead of concrete types? 

Example (_DBreezeBased.DocumentsStorage_)
Instead of :

``` c#
    public List<Document> AddDocuments(List<Document> docs) { }
```

Use:

``` c#
    public IList<Document> AddDocuments(IList<Document> docs) { }
```

**Comment by hhblaze** [comment]
Don't see any reason for that.

**Comment by vba** [comment]
It's a common practice, to use interfaces. There's no reason to force your users to use lists isn't? I found  it overkill to reuse a list in my F# code:

``` F#
    let docs = [
        new Document ()
        new Document ()
        new Document ()
    ]
    storage.AddDocuments(new List<Document>(docs)) |> ignore
```

Useless, especially when you need to make an important import.

**Comment by hhblaze** [comment]
Can't you make in F# smth. like 

storage.AddDocuments(docs) 
or 
storage.AddDocuments((List<Document>)docs)

as I understand "docs" is a list, but I am not programming F# and may understand it wrong.

**Comment by vba** [comment]
That's a point, in F# you have to use its own lists that implement IList but literally it's a different type. It's also impossible to use your API with LinkedList or another read-only list structures. Why such restriction?

**Comment by hhblaze** [comment]
ok, I have changed some public methods where I found List and have update NuGet to v. 1.20.

**Comment by vba** [comment]
Ok, thanks a lot

**Comment by hhblaze** [comment]
Let me now about other restrictions, thank you!
